### PR TITLE
fix(windows): add `/utf-8` flag for parsers using unicode symbols

### LINKED ISSUE #3222: Cannot use unicode in queries on windows in rust in tree-sitter 0.22.2
### Problem

On tree-sitter versions 0.21.0 and higher, attempting to compile a query containing a unicode character fails on windows using the rust bindings. The same code succeeds on linux and macOS, and succeeds across all platforms on 0.20.x versions:

```rust
use tree_sitter::{Parser, Query, QueryCursor};

fn main() {
    let mut parser = Parser::new();
    parser.set_language(&tree_sitter_test::language()).expect("Error loading grammar");
    let source_code = "op == expr op ≜ expr";
    let tree = parser.parse(source_code, None).unwrap();
    println!("{}", tree.root_node().to_sexp());

    let query = Query::new(&tree_sitter_test::language(), "(def_eq \"≜\" @def_eq)").unwrap();
    let mut cursor = QueryCursor::new();
    for capture in cursor.matches(&query, tree.root_node(), "".as_bytes()) {
        println!("{:?}", capture);
    }
}
```

### Steps to reproduce

1. Clone this branch containing a minimal tree-sitter grammar and rust program: https://github.com/ahelwer/tree-sitter-test/tree/windows-unicode
2. `cd` into the `rust` directory and run `cargo run`

On Windows, this will produce the following error value:
```
called `Result::unwrap()` on an `Err` value: QueryError { row: 0, column: 9, offset: 9, message: "", kind: NodeType }
```
On Linux and macOS, it will succeed.

Alternatively, you can see a less minimal cross-platform reproduction of it in this CI run: https://github.com/tlaplus-community/tlauc/actions/runs/8440383121

### Expected behavior

I expected to be able to continue using unicode characters in queries on all supported platforms. This behavior worked across all platforms when generating and consuming grammars with tree-sitter 0.20.x.

### Tree-sitter version (tree-sitter --version)

0.22.2, 0.21.0 or higher

### Operating system/version

N/A

### PR DESCRIPTION
**Pull request by amaanq**
Fixes #3222

### CODE REVIEW

**Comment by clason** [comment]
This also fixes issues with purescript, Haskell, and (possibly) Perl utf-8 queries in nvim-treesitter.

File: cli/loader/src/lib.rs [hunk 1]
```diff
@@ -592,6 +592,7 @@ impl Loader {
             }
             command
                 .arg("/link")
+                .arg("/utf-8")
```
Comment (ObserverOfTime) [inline cli/loader/src/lib.rs:595]: It should be before `/link` since it's not a linker flag.

File: cli/src/generate/grammar_files.rs [hunk 2]
```diff
@@ -261,9 +261,19 @@ pub fn generate_grammar_files(
...
-        })?;
+        missing_path_else(
+            path.join("build.rs"),
+            |path| generate_file(path, BUILD_RS_TEMPLATE, language_name),
+            |path| {
+                let build_rs =
+                    fs::read_to_string(path).with_context(|| "Failed to read build.rs")?;
+                if !build_rs.contains("/utf-8") {
+                    eprintln!("Updating build.rs with the /utf-8 flag for Windows");
+                    generate_file(path, BUILD_RS_TEMPLATE, language_name)?;
```
Comment (ObserverOfTime) [inline cli/src/generate/grammar_files.rs:272]: It might be better to print a warning here instead of replacing the file.

File: cli/src/generate/templates/build.rs [hunk 3]
```diff
@@ -8,6 +8,9 @@ fn main() {
     c_config.file(&parser_path);
     println!("cargo:rerun-if-changed={}", parser_path.to_str().unwrap());
 
+    #[cfg(target_os = "windows")]
+    c_config.flag("/utf-8");
```
Comment (ObserverOfTime) [inline cli/src/generate/templates/build.rs:12]:
```suggestion
    #[cfg(target_env = "msvc")]
    c_config.flag("-utf-8");
```

The flag should not be added in mingw and cc-rs uses dashes.

File: cli/src/generate/grammar_files.rs (hunk 2 above)
Comment (amaanq) [reply cli/src/generate/grammar_files.rs:272]: it'd be annoying for users that don't care about the rust grammar, but have this warning printed every time they run generate

File: cli/src/generate/templates/build.rs (hunk 3 above)
Comment (ObserverOfTime) [reply cli/src/generate/templates/build.rs]: `msvc` not `windows`

File: cli/src/generate/grammar_files.rs (hunk 2 above)
Comment (ObserverOfTime) [reply cli/src/generate/grammar_files.rs:272]: But users that do care about the rust bindings may have to edit them again.

File: cli/src/generate/templates/build.rs (hunk 3 above)
Comment (amaanq) [reply cli/src/generate/templates/build.rs]: oops, sorry

File: cli/src/generate/grammar_files.rs (hunk 2 above)
Comment (amaanq) [reply cli/src/generate/grammar_files.rs:272]: what if we just place it after `println!("cargo:rerun-if-changed={}", parser_path.to_str().unwrap());` instead of generating from the template?
