### PR TITLE
fix(lib): correct next sibling of zero width node

### LINKED ISSUE #3732: `nextSibling` of ZWT returns 2nd next sibling
### Problem

Running `.nextSibling` on a ZWT returns the sibling **after** the immediate next sibling

related: https://github.com/tree-sitter/tree-sitter/pull/3566

### Steps to reproduce

```js


module.exports = grammar({
	name: "nextsibling",
	extras: $ => [ ],

	rules: {
		source: $ => seq(
			'a',
			$._bc,
			'd',
			'e',
			'f',
		),

		_bc: $ => seq(
			'b',
			'c',
		),
	}
});
```

example text: `abdef`

locate the missing node `'c'` and run `node.nextSibling` on it

### Expected behavior

returns the immediate next sibling `'d'`

### Actual:
returns the 2nd next sibling `'e'`

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.24.1

### Operating system/version

Windows 11

### LINKED ISSUE #3930: v0.24.4 causes Neovim to freeze in some configurations
### Problem

When Neovim is used with the [nvim-treesitter-refactor](https://github.com/nvim-treesitter/nvim-treesitter-refactor) plugin and `highlight_current_scope` is enabled, Neovim can freeze when deleting text. This does not happen with v0.24.3.

See neovim/neovim#31163.

### Steps to reproduce

Steps are outlined in neovim/neovim#31163.

As a summary, run:
```sh
cd "$(mktemp -d)"
if [ "$(uname -s)" = Darwin ]; then
  download_url="https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-$(uname -m).tar.gz"
else
  download_url=https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
fi

curl -L "${download_url}" | tar xz
nvim-*/bin/nvim -u minimal.lua minimal.lua # see below for minimal.lua
```
Then, after `nvim` has started, press `15gg` and then `dd`.

And `minimal.lua`:
```lua
for name, url in pairs {
  ['nvim-treesitter'] = 'https://github.com/nvim-treesitter/nvim-treesitter.git',
  ['nvim-treesitter-refactor'] = 'https://github.com/nvim-treesitter/nvim-treesitter-refactor.git',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require'nvim-treesitter.configs'.setup {
  ensure_installed = { "cpp", },
  refactor = {
    highlight_current_scope = { enable = true },
  },
}
```

### Expected behavior

tree-sitter should not cause Neovim to freeze.

### Tree-sitter version (tree-sitter --version)

0.24.4

### Operating system/version

macOS 15.1

### PR DESCRIPTION
**Pull request by WillLillis**
There seems to be two issues at play here. Using the example from https://github.com/tree-sitter/tree-sitter/issues/3732: The first is that the call to `ts_node_parent` on missing node `c` returns `c`, when it should instead return the tree's root node `source_file`. The second issue was some byte bounds checking for ZWTs inside `ts_node__next_sibling`.

Closes #3732
Closes #3930

### CODE REVIEW

File: lib/src/node.c [hunk 1]
```diff
@@ -542,7 +542,8 @@ TSNode ts_node_parent(TSNode self) {
 
   while (true) {
     TSNode next_node = ts_node_child_containing_descendant(node, self);
-    if (ts_node_is_null(next_node)) break;
+    if (next_node.id == self.id
```
Comment (vanaigr) [inline lib/src/node.c:545]: I think this is a bug in `ts_node_child_containing_descendant()`, since it's not supposed to return the node itself. 
It has also been deprecated in favor of `ts_node_child_with_descendant()`. I think the updated version would look something like this:

```c
TSNode next_node = ts_node_child_with_descendant(node, self);
if (ts_node_is_null(next_node)) return ts_node__null();
if (next_node.id == self.id) break;
```

Comment (WillLillis) [reply lib/src/node.c:546]: Good point. However, using that exact code causes the library to hang when running the test suite. Just swapping `ts_node_child_containing_descendant` for `ts_node_child_with_descendant` seems to work though:

```c
TSNode next_node = ts_node_child_with_descendant(node, self);
if (next_node.id == self.id
    || ts_node_is_null(next_node)) break;
node = next_node;
```

File: cli/src/tests/node_test.rs [hunk 2]
```diff
@@ -306,6 +306,31 @@ fn test_parent_of_zero_width_node() {
...
+    let (parser_name, parser_code) = generate_parser_for_grammar(&grammar_json).unwrap();
+
+    let mut parser = Parser::new();
+    let language = get_test_language(&parser_name, &parser_code, None);
+    parser.set_language(&language).unwrap();
+
+    let tree = parser.parse("abdef", None).unwrap();
+
+    let root_node = tree.root_node();
+    let missing_c = root_node.child(2).unwrap();
```
Comment (maxbrunsfeld) [inline cli/src/tests/node_test.rs:329]: Could you add a pre-condition check that `missing_c` is a missing `c` node?

File: test/fixtures/test_grammars/next_sibling_from_zwt/corpus.txt [hunk 3]
```diff
@@ -0,0 +1,2 @@
+(source_file
```
Comment (maxbrunsfeld) [inline test/fixtures/test_grammars/next_sibling_from_zwt/corpus.txt:1]: This corpus file doesn't look like it's formatted right. There's supposed to be a source document followed by a separator line like `-----`, and then the expected parse tree.

**Review by maxbrunsfeld — COMMENTED** [review]
Thanks for tracking down this bug. I left a few questions.

File: test/fixtures/test_grammars/next_sibling_from_zwt/corpus.txt (hunk 3 above)
Comment (WillLillis) [reply test/fixtures/test_grammars/next_sibling_from_zwt/corpus.txt]: My bad, completely blanked on finishing this when I wrote up the initial tests.

File: cli/src/tests/node_test.rs (hunk 2 above)
Comment (WillLillis) [reply cli/src/tests/node_test.rs:329]: Good point! Does `assert!(missing_c.is_missing());` and `assert_eq!(missing_c.kind(), "c");` cover it?

**Comment by WillLillis** [comment]
Really not sure what's causing the `CI / checks (pull_request)` failure. The line number given in the error is incorrect (856 vs. 844), and it's pointing to a function that's already in the standard libary (`std::fs::File`).

<details>
<summary>Error Copied from the CI run:</summary>

```shell
error: a method with this name may be added to the standard library in the future
Error:    --> cli/loader/src/lib.rs:856:19
    |
856 |         lock_file.unlock()?;
    |                   ^^^^^^
    |
    = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `unlock(...)` to keep using the current method
    = note: `-D unstable-name-collisions` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unstable_name_collisions)]`
help: add `#![feature(file_lock)]` to the crate attributes to enable `File::unlock`
    |
4   + #![feature(file_lock)]
    |

error: could not compile `tree-sitter-loader` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:108: lint] Error 101
Error: Process completed with exit code 2.
```
</details>

**Comment by clason** [comment]
Why is that check running a nightly toolchain anyway? That seems brittle and unnecessary.

File: cli/src/tests/node_test.rs (hunk 2 above)
Comment (maxbrunsfeld) [reply cli/src/tests/node_test.rs:329]: Yeah, that’s perfect

File: lib/src/node.c [hunk 4]
```diff
@@ -541,8 +541,9 @@ TSNode ts_node_parent(TSNode self) {
   if (node.id == self.id) return ts_node__null();
 
   while (true) {
-    TSNode next_node = ts_node_child_containing_descendant(node, self);
-    if (ts_node_is_null(next_node)) break;
+    TSNode next_node = ts_node_child_with_descendant(node, self);
+    if (next_node.id == self.id
```
Comment (amaanq) [inline lib/src/node.c:545]: small nit, the condition isn't that long so i'd prefer it on the same line

**Review by amaanq — APPROVED** [review]
