### PR TITLE
fix(safety): mark functions that potentially deref a raw pointer as unsafe

### LINKED ISSUE #2537: Unsound FFI functions in `*/c_lib`
Disclaimer: This is closer to a nitpick than a serious vulnerability.

Many of the functions in `*/c_lib.rs` are unsound. Since these are part of the public API, even on the Rust side, I believe they should be marked `unsafe` if calling them from safe Rust can lead to UB.

As an example [ts_tagger_delete](https://github.com/tree-sitter/tree-sitter/blob/70766f53275612e363410f71f58ae8ef1351dd3e/tags/src/c_lib.rs#L70C58-L70C58) can lead to double free or out of bounds access in safe rust. A snippet demonstrating this in the playground, which can be checked with Miri: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b34b49cac043bf4101077d5a1ab7d786.

I've verified the same example locally using the actual function found in the `tree-sitter-tags` crate.

### PR DESCRIPTION
**Pull request by amaanq**
Closes #2537 

@oskgo can I get your thoughts on this?

### CODE REVIEW

**Comment by ahlinc** [comment]
@amaanq You didn't marked all needed things as unsafe, I'll add a commit.

File: highlight/src/c_lib.rs [hunk 1]
```diff
@@ -145,42 +152,60 @@ pub extern "C" fn ts_highlight_buffer_new() -> *mut TSHighlightBuffer {
     }))
 }
 
+/// Deleteis a [`TSHighlighter`] instance.
```
Comment (ahlinc) [inline highlight/src/c_lib.rs:155]: Misprint `Deleteis`

File: highlight/src/c_lib.rs [hunk 2]
```diff
@@ -145,42 +152,60 @@ pub extern "C" fn ts_highlight_buffer_new() -> *mut TSHighlightBuffer {
...
+///
+/// # Safety
+///
+/// `this` must be non-null.
```
Comment (ahlinc) [inline highlight/src/c_lib.rs:159]: > `this` must be non-null.

This is not enough guaranty for safety, it also should be a valid pointer to a valid structure.

**Comment by amaanq** [comment]
> @amaanq You didn't marked all needed things as unsafe, I'll add a commit.

I wasn't sure if all of them were needed to be marked, or just those derefing raw ptrs

File: highlight/src/c_lib.rs [hunk 3]
```diff
@@ -145,42 +152,60 @@ pub extern "C" fn ts_highlight_buffer_new() -> *mut TSHighlightBuffer {
...
-    drop(unsafe { Box::from_raw(this) })
+pub unsafe extern "C" fn ts_highlighter_delete(this: *mut TSHighlighter) {
+    drop(Box::from_raw(this))
 }
 
+/// Deleteis a [`TSHighlightBuffer`] instance.
+///
+/// # Safety
+///
+/// `this` must be non-null.
```
Comment (ahlinc) [inline highlight/src/c_lib.rs:169]: If you don't have a tension to write a real docs for all this C API funcs right now I'd suggest to remove all such template doc messages because they don't provide useful meaning.

Every function that receives a raw pointer is unsafe by default.

**Comment by ahlinc** [comment]
> I wasn't sure if all of them were needed to be marked, or just those derefing raw ptrs

Every function that receives raw pointers is unsafe by default because there is no guaranty that passed pointers are valid pointers and pointed structs are also valid.

**Review by ahlinc — APPROVED** [review]
