### PR TITLE
fix: don't use `__declspec(dllexport)` on windows

### LINKED ISSUE #3127: tree-sitter.DLL is missing almost all exports
### Problem

After commit f1eecf9, when I build tree-sitter.dll with zig for Windows (either x86 or x86_64), the resulting DLL is *only* exporting these functions:

-   ts_current_malloc
-   ts_current_calloc
-   ts_current_realloc
-   ts_current_free

### Steps to reproduce

1. Edit build.zig to build a DLL: change `addStaticLibrary` to `addSharedLibrary`
2. run `zig build` with the x86 platform being default
3. Inspect exported DLL symbols with dumpbin, DepencyWalker etc.

Only the 4 methods listed above are exported.

### Expected behavior

The DLL should export the full API.

### Tree-sitter version (tree-sitter --version)

current master

### Operating system/version

Windows 10 x86

### PR DESCRIPTION
**Pull request by amaanq**
using this makes every other symbol hidden by default; for whatever reason microsoft exposes every symbol unless `__declspec(dllexport)` is used, then only those marked with this are exported

Closes #3127

### CODE REVIEW

File: cli/src/generate/render.rs [hunk 1]
```diff
@@ -1346,7 +1346,7 @@ impl Generator {
         add_line!(self, "#endif");
         add_line!(self, "");
         add_line!(self, "#ifdef _WIN32");
-        add_line!(self, "#define TS_PUBLIC __declspec(dllexport)");
+        add_line!(self, "#define TS_PUBLIC");
```
Comment (maxbrunsfeld) [inline cli/src/generate/render.rs:1349]: Do we need this whole `TS_PUBLIC` thing at all? I don't remember what issue it solved.

Comment (amaanq) [reply cli/src/generate/render.rs:1349]: it's so if anyone decides to compile with `-fvisibility=hidden` the symbols are *still* exported anyways. sometimes it's nice to reduce the noise/visible symbols from the lib or parser, which might stem from the enums/symbol names in parser.c.

**Comment by lewis6991** [comment]
Looks like CI failed on windows not being to load symbols. You sure this PR was correct?

**Comment by amaanq** [comment]
libloading 0.8.2 broke it, I'll file an issue soon but we should probably pin exactly to 0.8.1 for now then
