### PR TITLE
fix(web): correct childWithDescendant() functionality

### LINKED ISSUE #4362: childWithDescendant does not work in web-tree-sitter wasm build
### Problem

I am using web-tree-sitter 0.25.3.

`childWithDescendant` always returns null instead of returning the node.

The issue can be reproduced in both node and web browser

### Steps to reproduce

```js
const { Parser } = require('web-tree-sitter');
const { Language } = require('web-tree-sitter');

async function test() {
  await Parser.init()
  const parser = new Parser();
  const JavaScript = await Language.load('website/public/parsers/tree-sitter-javascript.wasm');
  parser.setLanguage(JavaScript);
  const sourceCode = 'let x = 1; console.log(x);';
  const tree = parser.parse(sourceCode);
  const root = tree.rootNode
  console.log(root.toString())
  const child = root.children[0].children[0]
  console.log(child.toString())
  const a = root.childWithDescendant(child) // null
  console.log(a)
}
test()
```

### Expected behavior

a should be defined

### Tree-sitter version (tree-sitter --version)

0.25.3

### Operating system/version

node 20, Chome

### PR DESCRIPTION
**Pull request by ribru17**
This fix allows for more granular address control when marshalling nodes across WASM. This is necessary for node methods which accept another node as a parameter (i.e., `childWithDescendant()`)

Fixes #4362

### CODE REVIEW

File: lib/binding_web/lib/tree-sitter.c [hunk 1]
```diff
@@ -44,13 +44,13 @@ static inline void marshal_node(const void **buffer, TSNode node) {
...
-  node.context[2] = code_unit_to_byte((uint32_t)TRANSFER_BUFFER[3]);
-  node.context[3] = (uint32_t)TRANSFER_BUFFER[4];
+  node.id = buffer[0];
+  node.context[0] = code_unit_to_byte((uint32_t)buffer[1]);
+  node.context[1] = (uint32_t)buffer[2];
+  node.context[2] = code_unit_to_byte((uint32_t)buffer[3]);
+  node.context[3] = (uint32_t)buffer[4];
   node.tree = tree;
   return node;
 }
```
Comment (amaanq) [inline lib/binding_web/lib/tree-sitter.c:56]: It'd be cheaper to take an index parameter instead - shift the offset to start indexing the `TRANSFER_BUFFER` by `index * SIZE_OF_NODE`

File: lib/binding_web/src/node.ts [hunk 2]
```diff
@@ -522,7 +522,7 @@ export class Node {
    */
   childWithDescendant(descendant: Node): Node | null {
     marshalNode(this);
-    marshalNode(descendant);
+    marshalNode(descendant, TRANSFER_BUFFER + SIZE_OF_NODE);
```
Comment (amaanq) [inline lib/binding_web/src/node.ts:525]: take an index here

**Review by amaanq — CHANGES_REQUESTED** [review]

File: lib/binding_web/lib/tree-sitter.c [hunk 3]
```diff
@@ -44,13 +44,14 @@ static inline void marshal_node(const void **buffer, TSNode node) {
   buffer[4] = (const void *)node.context[3];
 }
 
-static inline TSNode unmarshal_node(const TSTree *tree) {
+static inline TSNode unmarshal_node(uint32_t index, const TSTree *tree) {
```
Comment (WillLillis) [inline lib/binding_web/lib/tree-sitter.c:47]: Can you swap the order of the arguments here?

**Review by WillLillis — APPROVED** [review]
