### PR TITLE
fix(cli): handle nested tags test files

### LINKED ISSUE #3955: nested tag test panic strangeness
### Problem

nesting folders in a test/tags causes a panic that language not found for a path

### Steps to reproduce

1. clone kylegoetz/tree-sitter-unison
2. create a test/tags/foo
3. run tree-sitter test
4. observe panic
5. rename *directory* `foo` to `foo.u`
6. run tree-sitter test
7. observe no panic

So something about the tag tests expect paths to have names that end in the file extension of an available language

### Expected behavior

I expect paths to not have to have a mock file extension matching an available grammar language

### Tree-sitter version (tree-sitter --version)

0.24.3

### Operating system/version

macos 15

### PR DESCRIPTION
**Pull request by amaanq**
- Closes #3955

### CODE REVIEW

File: cli/src/test_tags.rs [hunk 1]
```diff
@@ -49,47 +49,84 @@ pub fn test_tags(
...
-                        test_file_name.to_string_lossy().as_ref()
-                    ),
-                );
+        print!(
+            "{indent:indent_level$}",
+            indent = "",
+            indent_level = indent_level * 2
+        );
+        if test_file_path.is_dir() && test_file_path.read_dir()?.next().is_some() {
+            println!("{}:", test_file_name.into_string().unwrap());
```
Comment (WillLillis) [inline cli/src/test_tags.rs:76]: Any reason for the `unwrap()` instead of `test_file_name.to_string_lossy()`?

Comment (amaanq) [reply cli/src/test_tags.rs:76]: copied from https://github.com/tree-sitter/tree-sitter/blob/07aaf2322e0d5d7568d37e65cc7a951da252416b/cli/src/test_highlight.rs#L77

I don't really expect anyone to use non-utf8 filenames for a test file, though it doesn't hurt to use `to_string_lossy` (I'll update the other callsite)

Comment (WillLillis) [reply cli/src/test_tags.rs]: Makes sense! I don't really expect it to be an issue either, but it can't really hurt to use the lossy form here.

**Review by WillLillis — APPROVED** [review]
