### PR TITLE
enhancement: do not validate e-mail address during grammar init

### LINKED ISSUE #3994: tree-sitter init email parsing behavior should change
### Problem

The current email parsing just warns the user if the email address entered during initialization is invalid. It doesn't explain why.

Furthermore, the current email validator requires two things: at least one `@` and a `.`. That's the whole validation scheme.

This technically produces false negatives. The RFC specification for email addresses requires the domain part to be a dot-separated list of DNS labels **or an IPv4 or IPv6 address** surrounded by brackets.

As such, a domain name like `jsmith@[IPv6:2001:db8::1]`, which contains no dots, is a valid email address that would be rejected by `tree-sitter init`.

### Steps to reproduce

`tree-sitter init`

for email address, input jsmith@[IPv6:2001:db8::1] (which is a valid email address)

### Expected behavior

Personally, because email validation is very complex, I would recommend not attempting any attempt to validate email addresses: if the validator isn't correct, to what end does one exist in the codebase?

But if we were to keep email validation, then I recommend getting rid of the dot requirement (because it's incorrect validation), keeping the @ requirement, and then updating the error message to mention that an `@` is required (so the user knows exactly what they did wrong).

Technically the `@` isn't even required, but without one, the address is assumed to be local, which makes no sense for any publicly-available package (although internal grammars for companies conceivably could be local-only).

For reference, here are some developers who have written about why one should not bother trying to validate email addresses (unless you're writing an email server):

* https://blog.sinjakli.co.uk/2011/02/13/email-address-validation-please-stop/
* https://davidcel.is/articles/stop-validating-email-addresses-with-regex/ (recommending only look for the `@`)
* https://news.ycombinator.com/item?id=11414749 (HackerNews discussion about why one shouldn't bother parsing email addresses with links to a few blogs written by participants in the discussion)

### Tree-sitter version (tree-sitter --version)

0.24.3

### Operating system/version

macOS 15.0.1

### PR DESCRIPTION
**Pull request by kylegoetz**
fixes and will close #3994

Removed email validation and added explicit type parameter (`: String`) a few lines down because linter recommended it.

### CODE REVIEW

File: cli/src/main.rs [hunk 1]
```diff
@@ -588,20 +588,9 @@ impl Init {
             let email = || {
                 Input::with_theme(&ColorfulTheme::default())
```
Comment (amaanq) [inline cli/src/main.rs:589]:
```suggestion
                Input::<String>::with_theme(&ColorfulTheme::default())
```

File: cli/src/main.rs [hunk 2]
```diff
@@ -588,20 +588,9 @@ impl Init {
...
-                                Ok(())
-                            } else {
-                                Err("This is not a valid email address")
-                            }
-                        }
-                    })
                     .allow_empty(true)
                     .interact_text()
-                    .map(|e| (!e.trim().is_empty()).then_some(e))
+                    .map(|e: String| (!e.trim().is_empty()).then_some(e))
```
Comment (amaanq) [inline cli/src/main.rs:593]:
```suggestion
                    .map(|e| (!e.trim().is_empty()).then_some(e))
```
