### PR TITLE
fix: ensure function signatures in the API consistently show parameter names

### LINKED ISSUE #1958: `api.h` is inconsistent about omitting parameter names in function prototypes
Hello!

I've noticed that some of the parameter names in `api.h` are named, while others are unnamed, without any visible pattern.
If a PR is welcome for cleaning it up, for all function prototypes to include parameter names, I'd gladly tackle that.

### PR DESCRIPTION
**Pull request by amaanq**
Closes #1958

### CODE REVIEW

File: lib/include/tree_sitter/api.h [hunk 1]
```diff
@@ -655,62 +655,62 @@ bool ts_node_eq(TSNode, TSNode);
...
  * on a certain syntax node, and can be moved imperatively to different nodes.
  */
-TSTreeCursor ts_tree_cursor_new(TSNode);
+TSTreeCursor ts_tree_cursor_new(TSNode node);
 
 /**
  * Delete a tree cursor, freeing all of the memory that it used.
  */
-void ts_tree_cursor_delete(TSTreeCursor *);
+void ts_tree_cursor_delete(TSTreeCursor *_self);
```
Comment (ahlinc) [inline lib/include/tree_sitter/api.h:663]: You can use normal self without underscore here and in other places in the api.h file. It used with underscore in implementations due to macro expansions.

**Review by ahlinc — CHANGES_REQUESTED** [review]

File: lib/include/tree_sitter/api.h [hunk 2]
```diff
@@ -896,15 +896,15 @@ const char *ts_query_string_value_for_id(
...
+void ts_query_disable_capture(TSQuery *self, const char *name, uint32_t length);
 
 /**
  * Disable a certain pattern within a query.
  *
  * This prevents the pattern from matching and removes most of the overhead
  * associated with the pattern. Currently, there is no way to undo this.
  */
-void ts_query_disable_pattern(TSQuery *, uint32_t);
+void ts_query_disable_pattern(TSQuery *self, uint32_t);
```
Comment (ahlinc) [inline lib/include/tree_sitter/api.h:907]: Missed parameter name

File: lib/include/tree_sitter/api.h [hunk 3]
```diff
@@ -655,62 +655,62 @@ bool ts_node_eq(TSNode, TSNode);
...
+void ts_tree_cursor_reset(TSTreeCursor *self, TSNode node);
 
 /**
  * Re-initialize a tree cursor to the same position as another cursor.
  *
  * Unlike `ts_tree_cursor_reset`, this will not lose parent information and
  * allows reusing already created cursors.
 */
-void ts_tree_cursor_reset_to(TSTreeCursor *, const TSTreeCursor *);
+void ts_tree_cursor_reset_to(TSTreeCursor *_dst, const TSTreeCursor *_src);
```
Comment (ahlinc) [inline lib/include/tree_sitter/api.h:676]: The same as with self

File: lib/include/tree_sitter/api.h [hunk 4]
```diff
@@ -771,10 +771,10 @@ uint32_t ts_tree_cursor_current_depth(const TSTreeCursor *);
  * This returns the index of the child node if one was found, and returns -1
  * if no such child was found.
  */
-int64_t ts_tree_cursor_goto_first_child_for_byte(TSTreeCursor *, uint32_t);
-int64_t ts_tree_cursor_goto_first_child_for_point(TSTreeCursor *, TSPoint);
+int64_t ts_tree_cursor_goto_first_child_for_byte(TSTreeCursor *self, uint32_t goal_byte);
+int64_t ts_tree_cursor_goto_first_child_for_point(TSTreeCursor *self, TSPoint goal_point);
 
-TSTreeCursor ts_tree_cursor_copy(const TSTreeCursor *);
+TSTreeCursor ts_tree_cursor_copy(const TSTreeCursor *_cursor);
```
Comment (ahlinc) [inline lib/include/tree_sitter/api.h:777]: The same

**Review by ahlinc — CHANGES_REQUESTED** [review]

**Review by ahlinc — CHANGES_REQUESTED** [review]
Don't forget to regenerate Rust bindings as a last step.

**Review by ahlinc — APPROVED** [review]
